import {
  DashboardOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  UserOutlined,
  PictureOutlined,
  GiftOutlined,
  ShopOutlined,
  TeamOutlined,
  MailOutlined,
  SettingOutlined,
  TabletOutlined,
  FileTextOutlined,
  ToolOutlined
} from "@ant-design/icons";
import { APP_PREFIX_PATH } from "configs/AppConfig";

const dashBoardNavTree = [
  {
    key: "home",
    path: `${APP_PREFIX_PATH}/home`,
    title: "home",
    icon: "",
    breadcrumb: false,
    submenu: [
      {
        key: "sidenav.dashboard",
        path: `${APP_PREFIX_PATH}/home/dashbroad`,
        title: "sidenav.dashboard",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "sidenav.scheduler",
        path: `${APP_PREFIX_PATH}/home/scheduler`,
        title: "sidenav.scheduler",
        icon: ToolOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "sidenav.catalog",
        path: `${APP_PREFIX_PATH}/home/catalog`,
        title: "sidenav.catalog",
        icon: ShoppingCartOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "sidenav.catalog.products",
            path: `${APP_PREFIX_PATH}/home/catalog/products`,
            title: "sidenav.catalog.products",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "sidenav.catalog.categories",
            path: `${APP_PREFIX_PATH}/home/catalog/categories`,
            title: "sidenav.catalog.categories",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "sidenav.catalog.collections",
            path: `${APP_PREFIX_PATH}/home/catalog/collections`,
            title: "sidenav.catalog.collections",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "combo",
            path: `${APP_PREFIX_PATH}/home/catalog/combo`,
            title: "sidenav.catalog.combo",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "orders",
        path: `${APP_PREFIX_PATH}/home/orders`,
        title: "sidenav.orders",
        icon: ShoppingOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "customers",
        path: `${APP_PREFIX_PATH}/home/customers`,
        title: "sidenav.customers",
        icon: UserOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "listClients",
            path: `${APP_PREFIX_PATH}/home/customers/listClients`,
            title: "sidenav.customers.listClients",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "groupsClients",
            path: `${APP_PREFIX_PATH}/home/customers/groupsClients`,
            title: "sidenav.customers.groupsClients",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "banners",
        path: `${APP_PREFIX_PATH}/home/banners`,
        title: "sidenav.banners",
        icon: PictureOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "promoCodes",
        path: `${APP_PREFIX_PATH}/home/promoCodes`,
        title: "sidenav.promoCodes",
        icon: GiftOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "offlinePoints",
        path: `${APP_PREFIX_PATH}/home/offlinePoints`,
        title: "sidenav.offlinePoints",
        icon: ShopOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "addresses",
            path: `${APP_PREFIX_PATH}/home/offlinePoints/addresses`,
            title: "sidenav.offlinePoints.addresses",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "geofences",
            path: `${APP_PREFIX_PATH}/home/offlinePoints/geofences`,
            title: "sidenav.offlinePoints.geofences",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "staff",
        path: `${APP_PREFIX_PATH}/home/staff`,
        title: "sidenav.staff",
        icon: TeamOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "mailing",
        path: `${APP_PREFIX_PATH}/home/mailing`,
        title: "sidenav.mailing",
        icon: MailOutlined,
        breadcrumb: true,
        submenu: [],
      },
    ],
  },
];

const systemNavTree = [
  {
    key: "system",
    path: `${APP_PREFIX_PATH}/system`,
    title: "system",
    icon: "",
    breadcrumb: true,
    submenu: [
      {
        key: "settings",
        path: `${APP_PREFIX_PATH}/system/settings`,
        title: "sidenav.system.settings",
        icon: SettingOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "mobileApplication",
        path: `${APP_PREFIX_PATH}/system/mobileApplication`,
        title: "sidenav.system.mobileApplication",
        icon: TabletOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "logs",
        path: `${APP_PREFIX_PATH}/system/logs`,
        title: "sidenav.system.logs",
        icon: FileTextOutlined ,
        breadcrumb: true,
        submenu: [],
      },
    ],
  },
];

const navigationConfig = [...dashBoardNavTree, ...systemNavTree];

export default navigationConfig;
